[project]
name = 'Decentralized-Consciousness-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consciousness-exchange]
path = 'contracts/consciousness-exchange.clar'
clarity_version = 2
epoch = 2.5

[contracts.mind-state-tokenization]
path = 'contracts/mind-state-tokenization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
